name: 'Parse Semver Ref'
description: 'Parse a github ref (usually a tag) and extract the semver version, optional package scope, and optional package name.'
branding:
  icon: 'tag'
  color: 'black'
inputs:
  ref:
    description: 'The github ref to parse (e.g. refs/tags/v1.0.0, refs/tags/pkg@v1.2.3).'
    required: true
outputs:
  ref:
    description: 'The ref that was parsed'
  matched:
    description: '`"true"` if the ref matched the semver pattern, `"false"` otherwise.'
  major:
    description: 'The major version number from the tag (e.g. `1` from `refs/tags/v1.2.3`).'
  minor:
    description: 'The minor version number from the tag (e.g. `2` from `refs/tags/v1.2.3`).'
  patch:
    description: 'The patch version number from the tag (e.g. `3` from `refs/tags/v1.2.3`).'
  prerelease:
    description: 'The prerelease version from the tag (e.g. `alpha` from `refs/tags/v1.2.3-alpha`).'
  build:
    description: 'The build version from the tag (e.g. `build` from `refs/tags/v1.2.3+build`).'
  name:
    description: 'The package name from the tag (e.g. `pkg` from `refs/tags/pkg@v1.2.3`).'
  scope:
    description: 'The package scope (if any) from the tag (e.g. `org` from `refs/tags/@org/pkg@v1.2.3`).'
runs:
  using: 'node20'
  main: 'dist/index.js'
